
export const Permissions = {
  // Posts
  CREATE_POST: 'CREATE_POST',
  EDIT_POST: 'EDIT_POST',
  DELETE_POST: 'DELETE_POST',
  APPROVE_POST: 'APPROVE_POST',
  REJECT_POST: 'REJECT_POST',
  VIEW_POST: 'VIEW_POST',

  // Comments
  CREATE_COMMENT: 'CREATE_COMMENT',
  EDIT_COMMENT: 'EDIT_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  APPROVE_COMMENT: 'APPROVE_COMMENT',
  REJECT_COMMENT: 'REJECT_COMMENT',

  // Letters
  CREATE_LETTER: 'CREATE_LETTER',
  PUBLISH_LETTER: 'PUBLISH_LETTER',
  DELETE_LETTER: 'DELETE_LETTER',
  APPROVE_LETTER: 'APPROVE_LETTER',

  // Newsletters
  MANAGE_NEWSLETTERS: 'MANAGE_NEWSLETTERS',
  VIEW_NEWSLETTERS: 'VIEW_NEWSLETTERS',

  // Users
  BAN_USER: 'BAN_USER',
  UNBAN_USER: 'UNBAN_USER',
  SUSPEND_USER: 'SUSPEND_USER',
  VIEW_USERS: 'VIEW_USERS',

  // Moderation
  FLAG_CONTENT: 'FLAG_CONTENT',
} as const;

export type Permission = typeof Permissions[keyof typeof Permissions];
